title: MacGyver Sessions
page-top-title: MacGyver Sessions
top-section-bg-text: The MacGyver Sessions
home-subtitle: Novel, Exciting, Self-Made, Hacked, and/or Improvised Sensors, Data Acquisition, and Data Transmission Solutions for Earth and Space Science
copyright-text: ''
